### ISSUE TITLE
Add Edmodo API

### ISSUE THREAD

**Issue by JoseRivas1998** [JoseRivas1998/Student-PA#12]

**Comment by SirNickParks** [comment]
I don't think we'll be able to use the Edmodo API as not only does it require an Edmodo developer account (which is surprisingly hard to get). It requires a finished app and full SSL-Support which well... we can't really provide for this app quite yet. For now we're gonna have to rule Edmodo out until the end when we may have time to integrate it and get approval from the Edmodo staff.

**Comment by JoseRivas1998** [comment]
Ok sounds good, I will close the issue
